version: '3'

services:
  server:
    image: prediris-server:rf
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  client:
    image: prediris-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8501:8501
